### PR TITLE
Create shifted_eren_malkoc.py

### PR DESCRIPTION
**Pull request by erenmalkoc**
## Checklist
- [X] I have read the [CONTRIBUTING]
- [X] I have performed a self-review of my own code
- [X] I have run the code locally and it works as expected
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by erenmalkoc — COMMENTED** [review]
updated shifted_eren_malkoc.py

**Review by canbula — CHANGES_REQUESTED** [review]
Check your calculations and see the test results.

**Review by erenmalkoc — COMMENTED** [review]
updated shifted_eren_malkoc.py

**Review by erenmalkoc — COMMENTED** [review]
updated shifted_eren_malkoc.py

**Review by erenmalkoc — COMMENTED** [review]
Update shifted_eren_malkoc.py

**Review by erenmalkoc — COMMENTED** [review]
updated shifted_eren_malkoc.py

**Review by canbula — APPROVED** [review]

**Pull request merged**
