### PR TITLE
Create weighted_eren_malkoc.py

### PR DESCRIPTION
**Pull request by erenmalkoc**
## Checklist
- [X] I have read the [CONTRIBUTING]
- [X] I have performed a self-review of my own code
- [X] I have run the code locally and it works as expected
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by canbula — CHANGES_REQUESTED** [review]
- You need to use a default value for `with_replacement` to make it a keyword parameter.
- You need to shorten your code, the maximum allowed code amount is 10 lines.

**Review by canbula — CHANGES_REQUESTED** [review]
See the results of the tests.

**Review by erenmalkoc — COMMENTED** [review]
updated weighted_eren_malkoc.py

**Review by canbula — CHANGES_REQUESTED** [review]
You need to use `weights` in both cases.

**Review by erenmalkoc — COMMENTED** [review]
update weighted_eren_malkoc.py

**Review by canbula — CHANGES_REQUESTED** [review]
We need at least one blank line between `import` statements and the rest of the code. Also in `else` part, you can directly return the value, fix the unnecessary assignment.

**Review by erenmalkoc — COMMENTED** [review]
updated weighted_eren_malkoc.py

**Review by canbula — APPROVED** [review]

**Pull request merged**
